spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-120.railway.app:6317/railway
    username: postgres
    password: ZzroLRSfR5yhDEYhJbjc
  jpa:
    hibernate:
      ddl-auto: update
